### ISSUE TITLE
Create main flow sequence diagram

### ISSUE THREAD

**Issue by c0rrzin** [c0rrzin/pcs2044-compras#4]
Please post the link here

**Comment by ghost** [comment]
![seq_diagram](https://cloud.githubusercontent.com/assets/11429012/6771156/c09063d4-d0b5-11e4-86c6-78030d165cb8.png)

**Comment by ghost** [comment]
Vini, pelo que eu entendi era mais ou menos isso... ou o estoque gera a propria ordem de compra... e o usuario so altera algumas quantidades e confirma ou o usuário pode modificar o estoque diretamente (para corrigir eventuais erros). Faz sentido?
